before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64

  goarm:
    - '7'

  ignore:
    - goos: windows
      goarch: 'arm'

  binary: '{{ .ProjectName }}'

checksum:
  algorithm: sha256

dockers:
  - &image-def
    image_templates:
      - ghcr.io/unixfox/{{.ProjectName}}:{{ .Version }}-amd64
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
  - <<: *image-def
    image_templates:
      - ghcr.io/unixfox/{{.ProjectName}}:{{ .Version }}-arm64
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64/v8

docker_manifests:
  - &manifest-ghcrdef
    name_template: ghcr.io/unixfox/{{.ProjectName}}:{{ .Version }}
    image_templates:
      - ghcr.io/unixfox/{{.ProjectName}}:{{ .Version }}-arm64
      - ghcr.io/unixfox/{{.ProjectName}}:{{ .Version }}-amd64
  - <<: *manifest-ghcrdef
    name_template: ghcr.io/unixfox/{{.ProjectName}}:{{ .Version }}
